export class BreakPointConstants {
  static readonly XS: string = 'xs' //watch
  static readonly SM: string = 'sm' //phone
  static readonly MD: string = 'md' //folding
  static readonly LG: string = 'lg' //tablet
  static readonly CURRENT_BP: string = 'current_breakpoint'
}

export class SafeAreaConstants {
  static readonly TOP: string = 'top'
  static readonly BOTTOM: string = 'bottom'
}

export class ViewsConstants {
  static readonly HOME_VIEW: string = 'HomeView'
  static readonly CATEGORY_VIEW: string = 'CategoryView'
  static readonly SEARCH_VIEW: string = 'SearchView'
  static readonly SEARCH_RESULT_VIEW: string = 'SearchResultView'
  static readonly LOGIN_VIEW: string = 'LoginView'
  static readonly SETTING_VIEW: string = 'SettingView'
}

